### ISSUE TITLE
droping of php version

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Central#33]
Hello,
it's cool to follow the php version end of life, and I totally agree on the principle BUT for enterprise support it will be hard.

Why?
Because too many enterprise are late related to they PHP versions.  Whatever they reason. But because we don't follow semver, it's hard for them to see that this BC break have been made. By the way, with this system, it's impossible to have a support about a bug in a previous version ;)

**Comment by Jir4** [comment]
In an other hand, it's a bad habit in enterprise to not follow dependency's version. At my work we have some soft under php 4.4.8 and servers are hacked regularely.

**Comment by Grummfy** [comment]
Yes. Enterprise have bad habits. But honestly if fix a rule to try as
possible to follow the previous version of php. I think it could be enough
Le 1 févr. 2016 11:24 PM, "Dupont Yohann" <notifications@github.com> a
écrit :

**Comment by Hywan** [comment]
First, Hoa is a rolling-released software. So we are not supposed to have versions.

However, since this is a requirement for several users, we have designed the Rush Release, standing for Rolling Und ScHeduled release (http://hoa-project.net/En/Source.html#Rush_Release). This release system is **compatible** with **both** semver and rolling release. The format is: `x.y.m.d` where `x` has the exact same semantics than in the semver.

So, in some way, we follow semver if users are only concerned by backward compatibilities.

I guess we have no free room to discuss about that. Ho

**Comment by Hywan** [comment]
### Rolling release and semver

On one hand, Hoa is a rolling-released software. So we are not supposed to have versions.

However, since this is a requirement for several users, we have designed the Rush Release, standing for Rolling Und ScHeduled release (http://hoa-project.net/En/Source.html#Rush_Release). This release system is **compatible** with **both** semver and rolling release. The format is: `x.y.m.d` where `x` has the exact same semantics than in the semver.

So, in some way, we follow semver if users are only concerned by backward compatibilities.

I guess we have no free room to discuss about that. Hoa is rolling released. That's the basis. We are partly compatible with semver, that's a must have.

Now, because we are a rolling released software, we do not maintain old versions. `master` is the main branch. When a BC break is introduced, a new `master` branch is “created”, and so old one is just forgotten. We **do not** maintain several versions in parallel.

### PHP version dropping

Knowing that, on the other hand, we decided to drop PHP versions as soon as they are dropped by the PHP group itself. Why? For the sake of the ecosystem.

But we have rules here. Each time we drop a PHP version, we consider this as a BC break. Actually it is most of the time not, but we consider it is all the time.

So for a company that would like to stick on an old, unmaintain, unsecure and slow PHP version, good! I wish them the best. But we, Hoa, continue to evolve, with another `x` in the snapshot tag. Company will not receive any new updates **from us**, but they will not receive any new updates **from PHP neither**. I don't see any issue here.


Thoughts :-)?

**Comment by Grummfy** [comment]
For the version, I honestly don't care what we use. It's documented, so it's OK.

For the version, why all known librairies/framework, does maintain it? Because company ask it.

**Comment by Jir4** [comment]
`For the version, why all known librairies/framework, does maintain it? Because company ask it.`
http://symfony.com/doc/current/reference/requirements.html

**Comment by Hywan** [comment]
@Grummfy 
> For the version, why all known librairies/framework, does maintain it? Because company ask it.

In case we would provide a product, it would make sense. But since we are providing libraries, and since we are doing rolling release, then it does not make sense. Moreover, we do not have the man power to maintain more than 1 version per library. Currently, we have 53 libraries on Packagist. If we maintain at least 2 versions per libraries, it means to maintain **106 projects**! Good luck with that. It's already hard to maintain 53 projects so far.

Maybe in the future. But not today. I don't see any good reasons to do that. No company asked yet.

**Comment by Grummfy** [comment]
oki, this is pretty clear.
