### ISSUE TITLE
Configure Mirror on Pikacode

### ISSUE THREAD

**Issue by vonglasow** [hoaproject/Central#79]
We need to take github as repositories source.

**Comment by shulard** [comment]
Since I can't edit the default comment, I add the same list here :

- [ ] Contributions-Atom-Pp PP —the grammar description language from Hoa\Compiler— support in Atom.
- [ ] Contributions-Atoum-PraspelExtension Include Praspel inside atoum.
- [ ] Contributions-Emacs-Pp PP —the grammar description language from Hoa\Compiler— support in Emacs.
- [ ] Contributions-Provisioning Provisioning scripts related to Hoa.
- [ ] Contributions-Symfony-BenchBundle The Hoa\Bench Symfony2 bundle.
- [ ] Contributions-Symfony-ConsoleBridge Hoa\Console to Symfony bundle bridge.
- [ ] Contributions-Symfony-ConsoleBundle The Hoa\Console Symfony2 bundle.
- [ ] Contributions-Symfony-RulerBundle The Hoa\Ruler Symfony2 bundle.
- [ ] Contributions-Vim-Pp PP —the grammar description language from Hoa\Compiler— support in Vim.
- [ ] Contributions-Zsh-Hoa Hoa\Cli support (autocompletion & co.) in Zsh.
- [ ] Acl The Hoa\Acl library.
- [ ] Bench The Hoa\Bench library.
- [ ] Cache The Hoa\Cache library.
- [ ] Cli The Hoa\Cli library.
- [ ] Compiler The Hoa\Compiler library.
- [ ] Consistency The Hoa\Consistency library.
- [ ] Console The Hoa\Console library.
- [ ] Core The Hoa\Core library.
- [ ] Database The Hoa\Database library.
- [ ] Devtools The Hoa\Devtools library.
- [ ] Dispatcher The Hoa\Dispatcher library.
- [ ] Dns The Hoa\Dns library.
- [ ] Event The Hoa\Event library.
- [ ] Eventsource The Hoa\Eventsource library.
- [ ] Exception The Hoa\Exception library.
- [ ] Fastcgi The Hoa\Fastcgi library.
- [ ] File The Hoa\File library.
- [ ] Graph The Hoa\Graph library.
- [ ] Heap The Hoa\Heap library.
- [ ] Http The Hoa\Http library.
- [ ] Irc The Hoa\Irc library.
- [ ] Iterator The Hoa\Iterator library.
- [ ] Json The Hoa\Json library.
- [ ] Kitab The Hoa\Kitab library.
- [ ] Locale The Hoa\Locale library.
- [ ] Log The Hoa\Log library.
- [ ] Mail The Hoa\Mail library.
- [ ] Math The Hoa\Math library.
- [ ] Memory The Hoa\Memory library.
- [ ] Mime The Hoa\Mime library.
- [ ] Model The Hoa\Model library.
- [ ] Notification The Hoa\Notification library.
- [ ] Option The Hoa\Option library.
- [ ] Praspel The Hoa\Praspel library.
- [ ] Promise The Hoa\Promise library.
- [ ] Protocol The Hoa\Protocol library.
- [ ] Prototype The Hoa\Prototype library.
- [ ] Realdom The Hoa\Realdom library.
- [ ] Regex The Hoa\Regex library.
- [ ] Registry The Hoa\Registry library.
- [ ] Router The Hoa\Router library.
- [ ] Ruler The Hoa\Ruler library.
- [ ] Serialize The Hoa\Serialize library.
- [ ] Session The Hoa\Session library.
- [ ] Socket The Hoa\Socket library.
- [ ] Stream The Hoa\Stream library.
- [ ] String The Hoa\String library.
- [ ] Stringbuffer The Hoa\Stringbuffer library.
- [ ] Test The Hoa\Test library.
- [ ] Translate The Hoa\Translate library.
- [ ] Tree The Hoa\Tree library.
- [ ] Ustring The Hoa\Ustring library.
- [ ] View The Hoa\View library.
- [ ] Visitor The Hoa\Visitor library.
- [ ] Websocket The Hoa\Websocket library.
- [ ] Worker The Hoa\Worker library.
- [ ] Xml The Hoa\Xml library.
- [ ] Xmlrpc The Hoa\Xmlrpc library.
- [ ] Xyl The Hoa\Xyl library.
- [ ] Zformat The Hoa\Zformat library.
- [ ] Zombie The Hoa\Zombie library.

**Comment by shulard** [comment]
J'ai l'impression que le repo Paste n'existe pas sur Github : https://pikacode.com/hoaproject/Paste/

**Comment by shulard** [comment]
@vonglasow, je viens de faire la modification de l'adresse des miroirs. J'ai créé le projet String sur Pikacode et il manque le projet Paste sur Github. Pour le reste, la liste m'a l'air complète 😄.

**Comment by vonglasow** [comment]
@shulard yep you are right the repository `Paste` is not on github, we need to migrate it and also after verification I have found the repository `static` haven't any mirror.

**Comment by shulard** [comment]
I just discovered that I can access the repo list at : https://git.hoa-project.net/ 😄.

Yep you are right about Static...

**Comment by shulard** [comment]
I've created the Static mirror on Pikacode. Actually it mirror "http://git.hoa-project.net/Static.git" but will be updated with GitHub URL when the repo'll exist.

**Comment by vonglasow** [comment]
@shulard I have updated the Static repository on pikacode to use as mirror github. It looks ok for me. Anything to add before I close the ticket ?

**Comment by shulard** [comment]
Since we decided on IRC to remove Paste repository, maybe we need to remove it from Pikacode ?

**Comment by vonglasow** [comment]
Paste deleted on Pikacode.
